const actionTypes = {
  APPLIANCE: {
    LOAD_SUCCESS: 'LOAD_APPLIANCE_SUCCESS',
    LOAD_ERROR: 'LOAD_APPLIANCE_ERROR',
    SELECTED: 'SELECTED_APPLIANCE',
    DELETE_SELECTED: 'DELETE_APPLIANCE'
  },
  MODAL: {
    SHOW: 'SHOW_MODAL',
    HIDE: 'HIDE_MODAL'
  },
  API: {
    REQUEST: 'REQUEST_API',
    REQUEST_RESOURCE: 'REQUEST_RESOURCE_API'
  },
  RESOURCE: {
    LOAD_URL_SUCCESS: 'LOAD_RESOURCE_URL_SUCCESS',
    LOAD_URL_ERROR: 'LOAD_RESOURCE_URL_ERROR'
  }
};
export default actionTypes;
