const actionTypes = {
  APPLIANCE: {
    LOAD: 'LOAD_APPLIANCE',
    LOAD_SUCCESS: 'LOAD_APPLIANCE_SUCCESS',
    LOAD_ERROR: 'LOAD_APPLIANCE_ERROR',
    SELECTED: 'SELECTED_APPLIANCE',
    DELETE_SELECTED: 'DELETE_APPLIANCE'
  },
  MODAL: {
    SHOW: 'SHOW_MODAL',
    HIDE: 'HIDE_MODAL'
  },
  RESOURCE: {
    LOAD_LINKS: 'LOAD_RESOURCE_LINKS',
    LOAD_LINKS_SUCCESS: 'LOAD_RESOURCE_LINKS_SUCCESS',
    LOAD_LINKS_ERROR: 'LOAD_RESOURCE_LINKS_ERROR'
  },
  REQUEST: {
    CALL_ERROR: 'CALL_REQUEST_ERROR'
  }
};
export default actionTypes;
