const actionTypes = {
  APPLIANCE: {
    LOAD: 'LOAD_APPLIANCE',
    LOAD_SUCCESS: 'LOAD_APPLIANCE_SUCCESS',
    LOAD_ERROR: 'LOAD_APPLIANCE_ERROR',
    SELECTED: 'SELECTED_APPLIANCE',
    DELETE_SELECTED: 'DELETE_APPLIANCE',
    LOAD_OWNERS: 'LOAD_OWNERS_APPLIANCE',
    LOAD_OWNERS_SUCCESS: 'LOAD_OWNERS_APPLIANCE_SUCCESS'
  },
  USER: {
    LOAD: 'LOAD_USER',
    LOAD_SUCCESS: 'LOAD_USER_SUCCESS',
    LOAD_ERROR: 'LOAD_USER_ERROR',
    SELECTED: 'SELECTED_USER',
    DELETE_SELECTED: 'DELETE_USER'
  },
  MODAL: {
    SHOW: 'SHOW_MODAL',
    HIDE: 'HIDE_MODAL'
  },
  RESOURCE: {
    LOAD_LINKS: 'LOAD_RESOURCE_LINKS',
    LOAD_LINKS_SUCCESS: 'LOAD_RESOURCE_LINKS_SUCCESS',
    LOAD_LINKS_ERROR: 'LOAD_RESOURCE_LINKS_ERROR'
  },
  REQUEST: {
    CALL_ERROR: 'CALL_REQUEST_ERROR'
  },
  ERROR: {
    RUNTIME: 'RUNTIME_ERROR'
  }
};
export default actionTypes;
